### PR TITLE
Change of regionalization on subs of torrents.js

### PR DESCRIPTION
**Pull request by rpaggi**
I made this change because i saw the subtitle are PT-Br and the flag appears are PT-Pt.

Enjoy

### CODE REVIEW

**Comment by gnuns** [comment]
:+1:

**Comment by rpaggi** [comment]
:/

**Comment by impronunciable** [comment]
This is a fix for PT-Br. We can add a more general regionalization feature instead with little effort.

**Comment by rpaggi** [comment]
@danzajdband But which other regionalization problem we have? Lets fix it :D

**Comment by impronunciable** [comment]
What I mean is let's fix it for future regions too. Maybe you can set up an
array for region (i.e. es-es, es-ar, pt-pt, pt-br...).

**Comment by impronunciable** [comment]
Also thanks for contributing :)

**Comment by rpaggi** [comment]
Oh really, i forgot that, because i focused only in my language, so sorry.
Let's work on all languages available on subtitle api

**Comment by rpaggi** [comment]
@danzajdband why this change aren't merged? Any think are wrong?

**Comment by EvandroZanatta** [comment]
:+1:

**Pull request closed without merging**
