### PR TITLE
Added a test suite for languages

### PR DESCRIPTION
**Pull request by thibaultcha**
Hi there!

So I wrote a small test suite to ensure every string is translated in every language. You run it with `npm test`. The tests are not passing for now because the subtitles language strings are not translated in every language:

```
Property french not found in es.json
Property english not found in es.json
Property spanish not found in es.json
Property swedish not found in es.json
Property portuguese not found in es.json
Property romanian not found in es.json
Property turkish not found in es.json
Property swedish not found in fr.json
Property french not found in ja.json
Property english not found in ja.json
Property spanish not found in ja.json
Property swedish not found in ja.json
Property portuguese not found in ja.json
Property romanian not found in ja.json
Property turkish not found in ja.json
Property french not found in nl.json
Property english not found in nl.json
Property spanish not found in nl.json
Property swedish not found in nl.json
Property portuguese not found in nl.json
Property romanian not found in nl.json
Property turkish not found in nl.json
Property french not found in pt-br.json
Property english not found in pt-br.json
Property spanish not found in pt-br.json
Property swedish not found in pt-br.json
Property portuguese not found in pt-br.json
Property romanian not found in pt-br.json
Property turkish not found in pt-br.json
Property french not found in pt.json
Property english not found in pt.json
Property spanish not found in pt.json
Property swedish not found in pt.json
Property portuguese not found in pt.json
Property romanian not found in pt.json
Property turkish not found in pt.json
Property french not found in ro.json
Property english not found in ro.json
Property spanish not found in ro.json
Property swedish not found in ro.json
Property portuguese not found in ro.json
Property romanian not found in ro.json
Property turkish not found in ro.json
Property swedish not found in sv.json
Property french not found in tr.json
Property english not found in tr.json
Property spanish not found in tr.json
Property swedish not found in tr.json
Property portuguese not found in tr.json
Property romanian not found in tr.json
Property turkish not found in tr.json
```

But put aside from this PR, maybe this isn't right: why translate a language name in each other languages? First, this is duplication and leads to human errors (for example `de.json` has every language name translated BUT Deutsch...)
Why not let "English", "Français", and so on for each language? After all, **if I can't read the subtitles I don't expect the subtitles button to have a translated title**.

Anyway, let me know what you think of the test cases, is it useful, and what about those last thoughts ^^

### CODE REVIEW

**Comment by sirmackan** [comment]
I say keep the language names native in all languages, don't translate them.

**Comment by vinkla** [comment]
@sirmackan +1

**Comment by Patineta** [comment]
The language names are of the things that's bugging me. Maybe it's possible to create a basic list with common stuff (like language names, which should be in their original names) and then extend individual languages with that so we don't repeat ourselves. 
Do you want to add this so everything's tidy before the merge?

**Comment by thibaultcha** [comment]
I didn't quite get what's your idea, sorry ^^ Could you develop a little?

My idea about this yesterday was to put those languages in the reference language (let's say `en.json` as I set it or `es.json` if you want to change it later) and have a property:

```
"genres": {
  ...
},
"languages": {
  "english": "English",
  "french": "Français",
  ...
}
```

and so on. Only for the ref language, and in the test cases we handle it (and we test that the ref language has those language properties also)

**But we can't access it from other languages... Mhhhh.......**

**Comment by thibaultcha** [comment]
> and then extend individual languages

If I think right, you want to extend a basic language file (with languages props) for each language. Yes, that would be the best but I can't see a way to do this with JSON files.

**Comment by gnuns** [comment]
We can also create a 'languages.js' file with a var listing all available languages, something like:

```
var languages = {
    'en' : 'English',
    'pt-br' : 'Português/BR'...
```

**Comment by thibaultcha** [comment]
Yes but it would be separated from the `i18n` module which only works with JSON files I think.

But after all why not, since this is no translation anymore, why would we want to let them in the language section... We could have a custom JSON file with those language names string and load them via a custom method rather than using `i18n`.

**Comment by thibaultcha** [comment]
Should I do that then? Or do you want to merge and do it later on your own?

**Comment by thibaultcha** [comment]
New commit to dynamically load languages, so we are sure we don't forget one along the way, plus it's easier for future contributors to translate the app without having to search in the code, especially if they're not familiar with it.

**Comment by thibaultcha** [comment]
I see everybody translating languages names, adding languages, and creating a new PR just to add the language in `app.js`, new PR just to translate the new language names... (see 0c98379) it's a bit chaotic...

**Pull request closed without merging**
