### PR TITLE
Added fullscreen button

### PR DESCRIPTION
**Pull request by alexismarquis**

### CODE REVIEW

**Comment by abadfederico** [comment]
The full screen button has no style and is over the close button, with this update i cant minimize or maximize or even close the application because the button is over this controls (i can only access them in full screen)

If you want i can merge this pull request and adjust this problem and add an icon.

**Comment by alexismarquis** [comment]
You need to compile the _layout.scss

**Comment by abadfederico** [comment]
1clfizu

**Comment by abadfederico** [comment]
Thank you :D

**Pull request merged**
