### PR TITLE
Blue video player (#155)

### PR DESCRIPTION
**Pull request by wsyms**
This is to change the colors of the video player from red to blue. (https://github.com/popcorn-time/popcorn-app/issues/155)

screen shot 2014-03-06 at 5 30 04 pm

### CODE REVIEW

**Comment by barraponto** [comment]
Red is better ;) :bike:

**Comment by wsyms** [comment]
Red is in my opinion too Youtube-ish, this helps Popcorn Time create it's own identity. But in the end the community decides not just me. ;)

**Comment by luizfonseca** [comment]
+1. 

I second that @wsyms

**Comment by dimartiro** [comment]
+1 Blue

**Comment by abadfederico** [comment]
Blue it is!

**Pull request merged**
