### PR TITLE
Infinite Scroll Pagination

### PR DESCRIPTION
**Pull request by eduardomartines**
Infinite Scroll is much more intuitive, right?! (and seems that the normal pagination was fixed with about 5 pages or something)

So this is just what I did:
- I removed the code related with the normal pagination (sorry about that but I had to :)
- I added the (simple but powerful) logic for the infinite scroll pagination
- I updated the Search to can be paginated when the API start accepting the "page" parameter then we just have to uncomment a single line

I did my best (for now) to keep the code simple and clean ;)

### CODE REVIEW

**Comment by wsyms** [comment]
Great, can't wait to have this merged to the branch!

**Comment by eduardomartines** [comment]
@wsyms :+1:

**Comment by sirmackan** [comment]
Original issue in #62, great job!

**Comment by dimartiro** [comment]
can't wait

**Comment by Patineta** [comment]
That was a great contribution. Thanks a lot for resolving #62!

**Comment by sirmackan** [comment]
I tried it out now, it looks really nice! (y)

For me it only loads 100 movies though? :)

**Comment by Patineta** [comment]
It's a few more (we're changing that in a bit), but some categories don't have many movies that can be streamed without issues.

**Comment by eduardomartines** [comment]
@Patineta my pleasure ;)

**Pull request merged**
