### PR TITLE
Movie preview

### PR DESCRIPTION
**Pull request by jeremybarbet**
Redesigning a little bit the movie preview. I try to make the most simplest possible. I will make another pull request with a navigation between movies preview.

### CODE REVIEW

**Comment by abadfederico** [comment]
I love this new sidebar, but the flags are ok? i im doing something wrong? 
screen shot 2014-03-06 at 11 02 10 pm

**Comment by spacegauch0** [comment]
I fixed the problem with the flags. I'm gonna merge the request then push the fix.

**Comment by abadfederico** [comment]
@kerberoS you are such a nice guy <3

**Comment by jeremybarbet** [comment]
Oops something went wrong with these flags. :)

**Pull request merged**
