### PR TITLE
More subtitle options for various programmming languages

### PR DESCRIPTION
**Pull request by rpaggi**
I changed the queries limit and the app showed more options of subtitles languages.
If you have the app installed, need to do a App.Cache.clear()
If you have a new installation don't need do anything

### CODE REVIEW

**Comment by rpaggi** [comment]
This need more changes in the search system. But this slightly improves

**Comment by rpaggi** [comment]
Sorry, this change is broken, i'll work better on this

**Comment by abadfederico** [comment]
Look that the new version of substitles wont use opensubtitles!

**Comment by rpaggi** [comment]
Oh yes, i'll wait

**Pull request closed without merging**
