### PR TITLE
Fix package.json HEAD dependencies

### PR DESCRIPTION
**Pull request by gsamokovarov**
`npm install .` fails for me, with the latest changes. Its probably because of npm/npm#2349.

### CODE REVIEW

**Comment by mike1808** [comment]
+1

**Comment by Batistleman** [comment]
+1

**Comment by niyue** [comment]
+1

**Comment by ohwhen** [comment]
#528 fixes it..

**Comment by sanderversluys** [comment]
+1

**Comment by prcastro** [comment]
This issue can be closed now...

**Comment by Link-** [comment]
This fix is better than the one referenced in #528 (Mac OS X 10.9.2)

**Pull request closed without merging**
