### PR TITLE
Update es.json

### PR DESCRIPTION
**Pull request by amit-feldman**
Updated some words to their correct translation

### CODE REVIEW

**Comment by melonboy** [comment]
"Supenso" is wrong, the correct word is "Suspense". The translation for "All" is "Todos" but "Popular" is more appropriate.

**Comment by Foxandxss** [comment]
Yup yup, I agree with @melonboy

**Comment by amit-feldman** [comment]
The correct translation to Thriller would be "Suspenso" in spanish, I know that because I'm a native spanish speaker and at least that's the spanish name for that genre in particular. Suspense is an english word and the proper translation would be that of "suspenso", for us, the spanish speaker users.

**Comment by amit-feldman** [comment]
I agree with Popular, but then again, you could have both, Popular by the users and All, to see the whole library. Just a thought

**Comment by Foxandxss** [comment]
I am Spanish native (from Spain) and I never heard someone saying: Vamos a ir a ver una pelicula de suspenso.

I see you're from south america, maybe there is called that way. Maybe we should do two different spanish, latin and spain one.

**Comment by amit-feldman** [comment]
Y tampoco una película de suspense

**Comment by Foxandxss** [comment]
Yeah, it is just a difference between latin spanish and spain spanish :)

**Comment by amit-feldman** [comment]
Even Thriller fits better than suspense. These days almost everyone know that word. But I'm pretty sure, Suspenso is the correct word for this. I mean take it or leave it, but that should be the word.

Cheers :)

**Comment by Foxandxss** [comment]
I agree 200% with that, I would just leave Thriller, at least on Spain that is really really used.

**Comment by amit-feldman** [comment]
And also In latin america. Thriller it is.

**Comment by melonboy** [comment]
La verdad que yo también veo mejor usar "Thriller" ya que tanto en España como en Latinoamérica es usado y hay que buscar la traducción más neutra posible. También añadir que en España "Suspense" es la traducción correcta. http://lema.rae.es/drae/?val=suspense

**Comment by dimartiro** [comment]
Me sumo para apoyar la decision de dejar Thriller, todo el mundo sabe lo que significa.. Aunque es cierto que al menos en america latina suspenso es valido y muchas veces se escucha decir "vamos a ver una película de suspenso"

**Pull request merged**
