### PR TITLE
Improved pt-br translation

### PR DESCRIPTION
**Pull request by EvandroZanatta**

### CODE REVIEW

**Comment by EvandroZanatta** [comment]
"Eu concordo" would be used to accept terms of use. Have "Eu entendi" or "Eu compreendo" would be more correct because the user is reading a warning and then he says he understood what is being told.

**Comment by EvandroZanatta** [comment]
I believe that the term "Pesquisar" is used more in Brazil than "Procurar".

**Comment by pedrolucasmag** [comment]
;s no need to edit , it's just Synonyms

**Comment by EvandroZanatta** [comment]
@wopaum you think we should leave the way it is? 

I think I'll redo my commit with only other changes without changing "legalDisclaimerAccept" and "search".

**Comment by EvandroZanatta** [comment]
@mccraveiro  agrees to keep only the other changes, and leave it all translations of "legalDisclaimerAccept" and "search"?

**Comment by mccraveiro** [comment]
@EvandroZanatta I do but these changes I've already done on #349

**Comment by EvandroZanatta** [comment]
@mccraveiro but analize and see that my upgrade was made based on her. I created a "fork" of your code and changed a few things more. For example words with drop cap which is not the beginning of the sentence and it is not the name of something.

**Comment by EvandroZanatta** [comment]
@mccraveiro  @wopaum I'll redo my commit, directly in main file, without changing more delicate things.

**Pull request closed without merging**
