### PR TITLE
Create arabic.png

### PR DESCRIPTION
**Pull request by SerkZex**

### CODE REVIEW

**Comment by SerkZex** [comment]
how to add a picture to the flags?
i want to add this flag to the arabic subtitle i.imgur.com/Jh6SlI3.png

**Comment by web93onv** [comment]
You need to create a git repo locally, add your project files to that repo, commit them to the local repo, and then sync that repo to your repo on github.

**Comment by SerkZex** [comment]
@web93onv i made a new repo and sync the files to it.
https://github.com/HeyTech/popcorn-app3/blob/master/images/arabic.png

how can i submit it to this repo?

**Comment by web93onv** [comment]
Green button 'create pull request':
https://github.com/popcorn-time/popcorn-app

Click: compare across forks
Select: head fork - your fork

**Pull request closed without merging**
