### PR TITLE
Hungarian localization

### PR DESCRIPTION
**Pull request by zeppelin**
~~Work in progress, pls do not merge yet!~~
Ready to merge!

### CODE REVIEW

**Comment by mmcdole** [comment]
@zeppelin, if you weren't ready to have this merged why did you submit the PR?  If I were you I would have your changes remain in your fork while this remains a WIP and submit the PR when you are done.

**Comment by zeppelin** [comment]
@mmcdole hey, sorry! It's customary for some OSS projects, to recieve early feedback. Might not be too helpful here, but I couldn't avoid the old habits ;)

**Comment by zeppelin** [comment]
@mmcdole ah, one more thing while we're here: can you help me to get the subtitles working? They doesn't seem to show up, do I miss something?

**Comment by zeppelin** [comment]
@hunscream I've seen a couple PRs from you, how about us joining forces? ;)

**Comment by hunscream** [comment]
Well, I just want this awesome app in my native language. :)

**Comment by zeppelin** [comment]
@hunscream en is :) A feliratokkal elvileg megvolnek, megsem mukodik...

**Comment by hunscream** [comment]
Lehet itt anyanyelven is írni?
Szóval, igazából csak úgy átfutottam a témán, nem néztem körül teljesen, vannak fájlok ahova még be kellene illeszteni a magyart, mint például a player.js-ben (egy sor), de most nézem utólag, te már megtetted.
A feliratokat pedig egyeztethetnénk előre, például:
Mégse az legyen Mégsem, hivatalosabb.
A language/hu.json-ban pedig hibát vétettél, az egyik sor szerepel angolul, és magyarul is.
Animált helyett lehetne Animációs, Krimi helyett Bűnügyi, de a Krimi is elfogadott, amit én írtam, az szintén csak magyarosabb.
Mystery lehetne Misztikus, mégiscsak magyar, és létező film műfaj.
(Nem próbáltam ki az alkalmazást a magyar nyelvvel még.)

**Comment by zeppelin** [comment]
@hunscream lehet, max nem ertik :)
Esetleg Skype? Ugy gyorsabb. Usernevem: xeppelin

**Comment by zeppelin** [comment]
@mmcdole I see the app uses subapi.com, however [their JSON](http://subapi.com/popular.json) doesn't include Hungarian. Is there any way to contact them?

**Comment by zeppelin** [comment]
@mmcdole Ready to merge.

**Comment by zeppelin** [comment]
While Hungarian subtitles are supported as of this commit in theory, currently subapi.com doesn't provide any. #294 

Nonetheless, It's good to have it in the app, because when the support for such subs arrive, it should automagically appear for the users.

**Comment by zeppelin** [comment]
@hunscream Updated `language/hu.json` with your suggestions. Thank you!

**Comment by tothf** [comment]
@zazo-hun Thanks that you've let me know. I've closed that PR.

+1 for "Mégse" http://www.e-nyelv.hu/2010-12-28/megse-megsem/

Franky

**Comment by zeppelin** [comment]
@zazo-hun @tothf @hunscream Replaced "Mégsem" with "Mégse". Thank you guys! :)

**Comment by norbert-berenyi** [comment]
Mivel tudom Buildelni a projektet?

**Comment by Patineta** [comment]
@zeppelin Great job, guys! That's one of the most extensive translations I've seen yet. Merged and we'll use it on the next release.

**Comment by hunscream** [comment]
Great work guys! ;)

**Comment by zeppelin** [comment]
@bery08 https://github.com/popcorn-time/popcorn-app#building

**Comment by kisst** [comment]
@zeppelin Did you build it yourself and tested ? I just did with the latest version which already include this PR but no HUN subtitles are coming up.

About the build I'm planing to update the wiki, it's not trivial enough yet (imho)

**Comment by zosiu** [comment]
@kisst : I think subapi currenly doesn't support hungarian subs, that's why nothing shows up.

**Comment by zeppelin** [comment]
@kisst Unfortunately @LuckyThirteen [is right](https://github.com/popcorn-time/popcorn-app/issues/294#issuecomment-37349101). Subs should appear as soon as it get supported by subapi.com.

**Pull request merged**
