### PR TITLE
Add Romanian localization and subtitles

### PR DESCRIPTION
**Pull request by nickdima**
I still need to add the flag icon. Can you guys help me with this?

### CODE REVIEW

**Comment by fabe** [comment]
Here: http://c.fabe.im/UBsx

EDIT: Not sure but the icons should be from here: https://www.gosquared.com/resources/flag-icons/ (24x24)

**Comment by nickdima** [comment]
Thanks Fabe! Adding it now.

**Comment by nickdima** [comment]
OK, icon added, pull request complete.

**Comment by Patineta** [comment]
Thanks for the translation! It'll be available on the next release.

**Comment by nickdima** [comment]
Thanks for merging my pull request!

**Pull request merged**
