### PR TITLE
New quit confirmation

### PR DESCRIPTION
**Pull request by alexismarquis**
I made a replacement for the javascript confirm() at exit. Hope u'll like it !

### CODE REVIEW

**Comment by abadfederico** [comment]
Doesn't work for me :( 
Please test it again. Im on Mac OS

**Comment by alexismarquis** [comment]
I updated the css, it should be working now.

**Comment by abadfederico** [comment]
I like this new version. But you must edit the scss files not the css! 

I would love to see this implemented.

**Comment by alexismarquis** [comment]
I edited the scss ;)
look at  _layout.scss

**Comment by abadfederico** [comment]
My bad!
Thank you for this :D

**Comment by alexismarquis** [comment]
Happy to hear that ! Love that project :-)

**Pull request merged**
