### PR TITLE
subapi.com is replaced with http://yts.re, and many features was cut dow...

### PR DESCRIPTION
**Pull request by kemaldaggen**
Ok, this version is at least working, at least for time being. It uses yts.re to fetch movies and some features are disabled to make it work, such as, subtitles and quality selection. 

Here you can find precompiled executables for this fork
http://kemald.com/pt/popcorn.html

### CODE REVIEW

**Comment by pepijn809** [comment]
Awesome :+1: 
Its seems the development as in forks is moving this way
https://github.com/isra17/popcorn-app

Will anyone move along?

**Comment by schaitanya** [comment]
@pepijn809 +1

**Comment by kemaldaggen** [comment]
I was unaware that they also used yts.re api to replace notworking subapi.com, will look at https://github.com/isra17/popcorn-app

**Comment by pepijn809** [comment]
I don't know if they already fixed it but it would be awesome if many people joint the project of isra. So that we are united at last. Having many different version/forks and revisions is not where i would personally like to be.

**Comment by gabrielstuff** [comment]
I can confirm that this fork https://github.com/isra17/popcorn-app works perfectly with a nice redesign for scrapping torrent. Should be faster to integrate new torrent search for legal copy or anything else :)

**Comment by raulghm** [comment]
This fork is working, thanks!!

**Comment by thiagocifani** [comment]
Why I am not finding any subtitle option anymore? any thoughts?

**Comment by kirashi3** [comment]
@pepijn809 Yup I think that's the fork to move on to. Happy to help out any way I can, knowing little about programming but much about web design/HTML/CSS.

**Comment by kemaldaggen** [comment]
@thiagocifani I had to disable subtitles in order to get it working, but I am working on a subapi.com replacement to get it working as previous state.

**Comment by devguilleo** [comment]
@cettox let´s us know when u can make the sub works please or someone who can.

**Comment by notpushkin** [comment]
Pulled this into [my fork](https://github.com/unicorn-time/popcorn-app), thanks!

**Comment by jakefb** [comment]
Hi, I'm hoping to fork this and use it for an idea that I have had for a while now. My project has a similar goal to Popcorn Time but will focus more on using legal torrent content for creative purposes rather than being purely for entertainment. I have been wanting to do this for quite a while now because YouTube has become more commercial what makes it difficult for people to share there content, especially if it gets taken down because of YouTube's strict policy for enforcing copyright - most recently for video games. I have been trying to integrate torrent videos into a browser but don't know how to do it without using a browser plugin like btapp. I don't like having to install browser plugins (especially flashplayer) so I think it is best to go entirely web based (HTML5 and JavaScript) or cross-platform client based. Peerflix works very well so I think I will have use a client for the time being. I found out about Popcorn Time after it had stopped working but the GUI looks nice so I thought I might be able to use that. I don't know much JavaScript but know a bit of C I am learning it as I go along. If anyone has suggestions or would like to help me I am open to it. Cheers.

**Comment by kemaldaggen** [comment]
@juan1990 @thiagocifani subtitles are back online https://github.com/cettox/popcorn-app/releases

**Comment by kemaldaggen** [comment]
@codexgit check out some legal torrent sources at http://wiki.vuze.com/w/Legal_torrent_sites, but many of them lack api's so you have to parse html and get torrent files.

**Comment by kemaldaggen** [comment]
@ale110 thanks.

**Comment by jakefb** [comment]
@cettox Thanks I'm also trying to find a good way for people to upload torrent videos this could work http://burnbit.com/

**Pull request closed without merging**
