### PR TITLE
Use the https protocol instead of git

### PR DESCRIPTION
**Pull request by vonbirdie**
GitHub doesn't officially support the Git protocol anymore. Also the port used by git (9418) is blocked in some firewalls.

### CODE REVIEW

**Comment by 1ace** [comment]
> GitHub doesn't officially support the Git protocol anymore.

Where did you see that?

**Comment by cadesalaberry** [comment]
From github [help wiki](https://help.github.com/articles/which-remote-url-should-i-use), it makes sense to change to https.

> Use these URLs for users that are behind a firewall or proxy. Many firewalls will block the ssh URLs from working.

Also

> Tip: You don't have to enter your password every time you use an HTTPS URL, check out [this guide](https://help.github.com/articles/set-up-git#password-caching) for more info.

Basically it allows not dealing with ssh keys.

**Comment by GonzaGonza** [comment]
Nice, thanks!

**Comment by vonbirdie** [comment]
Also they didn't mention port 9418 on [this](https://help.github.com/articles/what-ip-addresses-does-github-use-that-i-should-whitelist) page before which made me mail them and ask why. Their response was that they didn't support it and that i should use HTTPS instead.

As far as i know you don't need to enter any credentials at all for HTTPS as long as you only need to read from the repo.

**Comment by vonbirdie** [comment]
But regardless the port is still blocked by a lot of firewalls so it they won't be able to build it as it is now :)

**Comment by zachlatta** [comment]
Honestly, if a firewall blocks the port for the Git protocol, it's likely they also block the ports for torrents.

**Comment by Patineta** [comment]
@luuse you make a good point. This should help a small subset of developers. Thanks!

**Comment by zachlatta** [comment]
@Patineta I don't think this was a good change. If port 22 is blocked, I'd be surprised if the ports for torrenting aren't.

**Comment by vonbirdie** [comment]
@zachlatta the git protocol doesn't run on port 22, it runs on port 9418. SSH runs on port 22 but it never used SSH.

While i mainly refer to corporate firewalls where Popcorn Time probably never will be built to begin with using HTTPS doesn't cause any problems and adds some security (the server will be verified with tls). Is there anything concrete about it you don't like?

**Comment by 1ace** [comment]
Well, that change seems to have [these consequences](https://aur.archlinux.org/packages/popcorntime-git/?comments=all#news) :/
For now I'll have to revert your changes locally…

**Comment by vonbirdie** [comment]
@1ace yeah, sorry, that's my bad :/. Had forgotten to make it git+https. NPM thinks it's regular tarballs now. I made a new pull request that fixes that. The popcornflix/peerflix problem seems to be related to 10bba98cba5a2884d97b23a914ba1d8f6093bb48 though?

**Comment by 1ace** [comment]
@luuse ~~I did not encounter that peerflix problem, but if it's still an issue,~~ it's indeed related to that commit.
Nevermind, I just hadn't tried the result of my compilation :/

**Pull request merged**
