### PR TITLE
Regionalization of subtitles(Pt-Br/Pt-Pt)

### PR DESCRIPTION
**Pull request by rpaggi**
Now the subtitles system download in portuguese of brazil and portuguese of Europa.

enjoy

### CODE REVIEW

**Comment by rpaggi** [comment]
Sorry the varios commits

**Comment by caiodias** [comment]
This is already implemented.

**Comment by rpaggi** [comment]
In subtitle system?
I don't see any change about it

**Comment by rpaggi** [comment]
Now the subititle system download subtitles in Pt-BR and Pt-PT

**Comment by caiodias** [comment]
I'm sorry rpaggi, I just translate the language packs for the interface. Just forget my comment.

**Comment by Patineta** [comment]
Love the new subs! Thanks!

**Pull request merged**
