### PR TITLE
Readme clean node module

### PR DESCRIPTION
**Pull request by gabrielstuff**
Hi there,

I took the time, to clean the node_module, correct the Readme for future contributors.

I think last push miss some files, as I'm not able to get master to run. See last issue open : https://github.com/popcorn-time/popcorn-app/issues/90

Thanks !

### CODE REVIEW

**Comment by GonzaGonza** [comment]
Nice!
Also take a look at the branch https://github.com/popcorn-time/popcorn-app/tree/no_modules

**Comment by Patineta** [comment]
Hi Gabriel, Thanks for the cleanup! I have a few comments to make:

Some of the packages (superagent and peerflix) require quite a few modifications in order to work properly, specially since peerflix is not being maintained anymore and has some _seriously_ outdated dependencies. That's why we put node_modules in the repo, so you can run the app without fiddling with a ton of packages. The right way of doing this, of course, is to refactor the code and put those customized packages outside node_modules, which we haven't done yet.
The same goes for node-webkit, as it requires a very specific .dll / .so to run videos. This is less of a PITA, but it simplifies the build process a lot.

README also is outdated, as we're using node-webkit v 0.9.2, which fixes a huge issue with CPU usage.

**Comment by impronunciable** [comment]
We should fork the modules that need modifications and use our own versions. Until that we have to keep the modules here.

**Comment by GonzaGonza** [comment]
I couldn't agree more.
I think we should work this on a separate branch. [no_modules](https://github.com/popcorn-time/popcorn-app/tree/no_modules)
The repo is bigger and bigger, and if the PR from @jhbruhn [Added support for grunt-node-webkit-builder](https://github.com/popcorn-time/popcorn-app/pull/102) works fine this is the way we should go.

**Comment by gabrielstuff** [comment]
I'm doing this for some of my projects, waiting until one day the owner will merge :)

This is fast and very smart.

You could fork to your organization and update the package.json.

I can do that, up to you !

we should rewrite commit history to remove any node_modules / config.js and thus win on size of the repo and security of the API Key.
++

**Comment by GonzaGonza** [comment]
@gabrielstuff I was working on this on the no_modules branch
https://github.com/popcorn-time/popcorn-app/blob/no_modules/
Take a look at it and make any suggestion.
Thanks!

**Pull request closed without merging**
