### PR TITLE
Update package.json to follow npm standard for github modules

### PR DESCRIPTION
**Pull request by ghost**
Building does not work correctly (at least in windows) if you include the full github url to your package (it will try to download the github html as a tgz file and then run it). The convention is instead the username/package format.

### CODE REVIEW

**Comment by ternel** [comment]
:+1: thx ;)

**Comment by clehner** [comment]
I was getting errors from npm about things being "not a package", but applying this patch allowed the dependencies to install properly. node -v v0.10.26, npm -v 1.4.3, OS X 10.9.2

**Comment by GonzaGonza** [comment]
Thanks!
It seems yesterday there was a PR with changes from git url to https and
that break things.

**Comment by Patineta** [comment]
#528 should have fixed this issue. Thanks! We can reopen this if the issue persists.

**Pull request closed without merging**
