### PR TITLE
Fix #128: be slightly more obvious about the title bar close icon

### PR DESCRIPTION
**Pull request by LightDust**
Fixes https://github.com/popcorn-time/popcorn-app/issues/128 for Beta 3 Milestone

### CODE REVIEW

**Comment by jduncanator** [comment]
To be honest, I'd have simply colored the close button red to emphasize its presence. Then when hovered it can be tinted dark. That way you maintain style consistency and don't have slightly larger buttons here and there. What do you think?

**Comment by LightDust** [comment]
Your idea is good too.
I thought the problem was that users could not guess what was green and yellow for.
In my opinion the green button is redundant with the fullscreen toggle.

**Comment by jduncanator** [comment]
Full screen overlays everything including the task bar. The maximise button simply fills the User space screen.

**Comment by ivantodorovich** [comment]
https://github.com/popcorn-time/popcorn-app/pull/644 PR to fix a bug with maximize/fullscreen

**Comment by martuanez** [comment]
Hi there the app is now here:
https://github.com/popcorn-official/popcorn-app

**Pull request closed without merging**
