### PR TITLE
Introduce Bulgarian locale and subtitle support

### PR DESCRIPTION
**Pull request by gsamokovarov**
I started the translation with a little knowledge of the code base and I added some keys to the opensubtitles and yifysubtitles providers. Are you guys deprecating those?

Also, do you control subapi.com? Can you make it find Bulgarian subtitles too?

### CODE REVIEW

**Comment by zbrox** [comment]
Доколкото виждам сме се дублирали - #462 И на мен не ми беше ясно за субтитрите, затова просто направих като теб и нацъках всичко. :)

**Comment by gsamokovarov** [comment]
Yeah, missed that. Sorry for the dup :)

Wanna combine the efforts? For example I love your flag (as my colors sucks), but I also like that the genres in my translation are all in singular form. 

_( Let's keep the conversation in English, so the other guys can follow it as well :)_

**Comment by zbrox** [comment]
Yeah, that would be great.

To be honest I wasn't sure if I should've kept them singular or not, I 
just had some sort of a "return to the childhood" moment and remembered 
how they were in the local video rental store :) I agree it's best to be 
consistent and keep 'em all in singular.

**Comment by gsamokovarov** [comment]
:+1:

**Comment by zbrox** [comment]
I pushed the genre translations from your bg.json file. I made two small changes - one fixed typo and also I changed the case of "Научна фантастика", because technically in Bulgarian only the first one should be upper case. I hope that seems ok.

**Comment by gsamokovarov** [comment]
Yep, seems great.

**Pull request closed without merging**
