### PR TITLE
Add Always-on-top

### PR DESCRIPTION
**Pull request by kristofferR**
Make the app stay on top.

### CODE REVIEW

**Comment by SerkZex** [comment]
ehh noo, what about if i want to surf during the movie?

**Comment by Patineta** [comment]
We might make this into a setting, but it's a very strong default to ship with the app. Thanks anyway!

**Comment by kristofferR** [comment]
@HeyTech That's exactly what this is for. This enables you to surf while the app is still visible in the corner of your screen.

**Comment by kristofferR** [comment]
@Patineta That's okay. However it is not that of a strong default setting, MPlayerX ships with it by default on OS X for example.

**Pull request closed without merging**
