### PR TITLE
Sentence correction.

### PR DESCRIPTION
**Pull request by WikiDZe**
Sentence correction.

### CODE REVIEW

**Comment by ukd1** [comment]
@WikiDZe why change the indentation?

**Comment by WikiDZe** [comment]
@ukd1 Correction of a sentence which has changed direction.

**Comment by ukd1** [comment]
@WikiDZe you've also re-indented half the file - see L2 before and after. You should undo that and leave just your change.

**Comment by Patineta** [comment]
@WikiDZe we changed all language files to two spaces. Can you change just the modified line and resubmit? This makes the merge a bit more complicated otherwise. Thanks!

**Pull request closed without merging**
