### PR TITLE
Ukrainian language

### PR DESCRIPTION
**Pull request by web93onv**
I was not sure which files can be changed. I changed everything that I have seen.

### CODE REVIEW

**Comment by ghost** [comment]
I think it should be UA not UK

**Comment by web93onv** [comment]
No, UA = Ukraine (country).
uk - ukrainian language.

http://en.wikipedia.org/wiki/Language_code
http://en.wikipedia.org/wiki/List_of_ISO_639-2_codes

**Comment by ghost** [comment]
Sorry, my bad.

**Comment by Patineta** [comment]
@web93onv Thanks for the translation! We'll use it on the next release.

**Pull request merged**
