### PR TITLE
Add greek subs & fix greek localization

### PR DESCRIPTION
**Pull request by comzeradd**
- Added support for Greek subtitles from opensubtitles.org
- s/gr/el/: Renamed the Greek translation to el, which is the right 2-word locale code

### CODE REVIEW

**Comment by comzeradd** [comment]
Fixes #325

**Comment by ageorgios** [comment]
+1

**Comment by zzecool** [comment]
+1 please add this one

**Comment by yannisc** [comment]
+1

**Comment by comzeradd** [comment]
This repo is no longer maintained. The project has been forked [here](https://github.com/popcorn-team/popcorn-app). I opened the [same PR](https://github.com/popcorn-team/popcorn-app/pull/513).

**Pull request closed without merging**
