### PR TITLE
Bengali translation

### PR DESCRIPTION
**Pull request by pyprism**
Add Bengali translation

### CODE REVIEW

**Comment by spacegauch0** [comment]
@pyprism thank you very much for your support buddy! Could you please translate legalDisclaimerResponsible, legalDisclaimer and subtitledIn so I can merge this?

**Comment by pyprism** [comment]
Ok .

**Comment by pyprism** [comment]
Done

**Comment by spacegauch0** [comment]
Well done buddy! Thank you!

**Pull request merged**
