### PR TITLE
Update es.json

### PR DESCRIPTION
**Pull request by josemmo**
Changed from formal ("Usted") to colloquial ("tú")
Updated some strings which were updated in "en.json"

### CODE REVIEW

**Comment by Subv** [comment]
I don't think video should have a tilde

**Comment by josemmo** [comment]
According to RAE, "vídeo" it's OK, but I think both words are accepted. http://lema.rae.es/drae/?val=v%C3%ADdeo

**Comment by devguilleo** [comment]
yeah but I think is better the way it´s was before,  with usted or vos. I know that some people use different spanish but we can´t lost time with this...becouse we can´t all agree. It depends where are you from but there is no wrong words...so why to change? video, descargala y subtítulos quedaba mejor antes.

**Comment by montogeek** [comment]
Both are accepted, I prefer vídeo.

**Comment by scumah** [comment]
In my opinion, with the app having no country-specific languages support, [Standard Spanish](http://en.wikipedia.org/wiki/Standard_Spanish), used mostly everywhere in this cases, should be the choice. Of course, since the team is based in Argentina, they may feel more confortable using their Spanish, which is completely rightful.

**Comment by josemmo** [comment]
I agree with scumah. I propose creating two language files: "[es-419.json](http://en.wikipedia.org/wiki/Language_code)" for Latin America and "es.json" for Standard Spanish.
In fact, most popular apps have both alternatives and movies are dubbed in Spanish for Latin America and Spanish for Spain.

**Comment by josemmo** [comment]
Wait... I've just realised this project is closed. http://getpopcornti.me

**Pull request closed without merging**
