### PR TITLE
initial pass at movie tile view improvement

### PR DESCRIPTION
**Pull request by samccone**
Hi Friends, incase you have not heard of https://github.com/marionettejs/backbone.marionette I would recommend checking it out! This library will save you guys so many headaches and improve the view logic of this repo greatly. 

I took an initial pass on the movie view for you!

Let me know, and would love to chat about it more.

### CODE REVIEW

**Comment by Patineta** [comment]
@samccone Quick question: How well does this work and which issues does it fix/improve? (For instance the Popular > Other Category > Popular flow ruins the popular page right now, which is due to what we call the Pages Clusterfuck).
We're working to get the issues to a more manageable level ASAP and reviewing pull requests for quality takes a very long time, so this would be of huge help. Thanks!

**Comment by samccone** [comment]
#### How well does this work and which issues does it fix/improve?
- this is a refactor of the movie tile view (improves the code and is non breaking), on a larger scale marionette is a collection of common design and implementation patterns. aka it will make writing and maintaining this app MUCH simpler. 

Using raw backbone views is basically like reinventing the wheel, marionette takes the common patterns and abstracts them for you, while being super performant! 

Let me know if you have any other questions.

**Comment by samccone** [comment]
On a side note @Patineta I can fix this bug for you on the filter using marionette. Will do that next on this branch.

**Comment by Patineta** [comment]
@samccone Thanks a lot! Also I've seen you added the fix for the Windows 8.1 crash, which is very nice as well.

**Pull request merged**
