### PR TITLE
Fix the git https urls in package.json

### PR DESCRIPTION
**Pull request by vonbirdie**
My pull request #431 changed the urls to use https for the git dependencies in package.json but i had forgotten that npm requires it to be git+https to interpret them as git urls. Without the git+ part npm [thinks](https://www.npmjs.org/doc/json.html#Git-URLs-as-Dependencies) it's a tarball.

Sorry, my bad!

### CODE REVIEW

**Comment by ohwhen** [comment]
Oops...I just fixed it in my branch and submitted a duplicate pull request #531. Thanks for fixxing it, took me a little while to found out why my npm build didn't work. :)

**Comment by ohwhen** [comment]
@luuse perhaps there should be a clean task in the gruntfile, that cleans out the build folders? Because right now the build fails with a `(ENOTEMPTY, directory not empty` message. It should be possible with this grunt task https://github.com/gruntjs/grunt-contrib-clean

**Comment by vonbirdie** [comment]
@ohwhen I can't reproduce that and it doesn't feel like it has anything to do with this or? I agree with your that there probably should be a clean task

**Comment by ohwhen** [comment]
When you run the Grunt build twice, it gives me an error (for the Mac build) complaining that the folder is not empty.

But true, it isn't related to this PR...I hesitate to open up another PR before this fix is accepted.

**Comment by edgardz** [comment]
You need to put a 'git+' prefix before the dependency URL in package.json, like:
...
"adm-zip" : "git+https://github.com/gpt-modules/adm-zip.git",
...

**Comment by gvangool** [comment]
If this is merged, it will also fix #516 and #521. But it will conflict with #540.

**Comment by Patineta** [comment]
We're merging this one just to get this out of the way. Thanks!

**Pull request merged**
