### PR TITLE
Add button to change subtitle color.

### PR DESCRIPTION
**Pull request by tapajos**
This PR creates a button on the control panel to change the subtitle color to Yellow.

I don't think that this change should be accepted as it is now. I created this PR to start a discussion on the best way to make it and share an issue that I found.

My initial ideia was to make this button a toggle that changes between white and yellow. The problem is that a click in any button on control bar is triggering the onClick twice, making it really hard to create a toggle. Any idea on why this is happening?

### CODE REVIEW

**Comment by emerleite** [comment]
+1

**Comment by abadfederico** [comment]
Nice! I like it. we need a settings view as soon as possible!

**Comment by andrewvergel** [comment]
Good

**Comment by caffo** [comment]
+1

**Comment by fabiojansen** [comment]
+1

**Comment by caruccio** [comment]
:+1: Yellow is definitely the best color for subtitles. It would be nice to allow user to select the color too.

**Comment by HatScripts** [comment]
I certainly prefer white as my subtitle colour. It would be really nice to have a full-on customisation interface (colour, size, font, outline, shadow, etc.) for subtitle appearance, like [the one in VLC](http://i.imgur.com/RR503vS.png).

**Comment by tapajos** [comment]
I'm still trying to figure out why it is triggering the event twice.

**Comment by EvandroZanatta** [comment]
@HatScripts +1
@tapajos you have my support (+1)

**Comment by maracaipe** [comment]
:+1:

**Comment by GonzaGonza** [comment]
i will work on it from here. Thanks for the PR :+1: @tapajos

**Comment by gentilfp** [comment]
+1

**Comment by EvandroZanatta** [comment]
@GonzaGonza this will be implemented for version 3?

**Comment by davidgumberg** [comment]
Hey! Thanks for the contribution! Unfortunately this project is no longer being maintained, but it is being forkd by the very reputable folks at YiFy, so please resubmit your pull request to: https://github.com/Yify/popcorn-app

**Pull request closed without merging**
