### PR TITLE
Improve infinite scroll rendering

### PR DESCRIPTION
**Pull request by PerfectSlayer**
Fix third point of #391

### CODE REVIEW

**Comment by eduardomartines** [comment]
:+1:

**Comment by PerfectSlayer** [comment]
Could be fine if the infinite scroll fixes be merged.
I could continue to improve UX and rendering about it.

**Comment by SerkZex** [comment]
can't you make it with every category?

**Comment by PerfectSlayer** [comment]
Infinite scroll is available for each categories and popular movies (not for search).

I'm trying to improve CSS animation but the page and genre variable bug does not help to make tests…

**Pull request merged**
