### PR TITLE
Update yifysubtitles.js

### PR DESCRIPTION
**Pull request by SerkZex**

### CODE REVIEW

**Comment by SerkZex** [comment]
Sorry i don't know how to commit them all together :/

Update yifysubtitles.js #637 
Update torrents.js #636 
Update opensubtitles.js #635 
Update player.js #634 
Update app.css #633 
Update sidebar.js #630 
Update _moviedetails.scss #629

**Comment by mciparelli** [comment]
You could have asked?

```
git checkout -b css_js_fixes
git add 1.js
git commit -m 'patch-1'
git add 2.css
git commit -m 'patch-2'
git push -u <your-repo> css_js_fixes
```

send the pull request

**Comment by SerkZex** [comment]
@mciparelli were should i put that code?

and how can i send this picture to the pull?
https://github.com/HeyTech/popcorn-app3/blob/master/images/arabic.png

**Comment by mciparelli** [comment]
@HeyTech are you really asking me where to put six lines starting with 'git'?
I can only assume you don't know what git is even though you are writing here. 
I would recommend you to close your pull requests, have [it](http://git-scm.com/documentation) a read, then use the code I gave you and come back with one pull request that includes all your translation changes.

**Comment by SerkZex** [comment]
@mciparelli i don't need to read, i learn by mistakes and someone tells me.. reading is boring... 
when i press " compare across forks." i get the last i edited in my fork and not only the picture.. how can i delete the others? 
https://f.cloud.github.com/assets/6899838/2414390/013016ca-aaea-11e3-90ff-fd0bcf22422a.png

**Pull request closed without merging**
